schema {
  query: Query
}

type Query {
  orders(
    skip: Int
    take: Int
    where: OrderListItemFilterInput @cost(weight: "10")
    order: [OrderListItemSortInput!] @cost(weight: "10")
  ): OrdersCollectionSegment
    @listSize(
      assumedSize: 20
      slicingArguments: ["take"]
      slicingArgumentDefaultValue: 20
      sizedFields: ["items"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
}

"Information about the offset pagination."
type CollectionSegmentInfo @shareable {
  "Indicates whether more items exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more items exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
}

type OrderItemListItem {
  productId: UUID!
  product: ProductListItem!
  quantity: Int!
  price: Decimal!
}

type OrderListItem {
  id: UUID!
  customerId: UUID!
  orderName: String!
  itemCount: Int!
  totalPrice: Decimal!
  items: [OrderItemListItem!]!
}

"A segment of a collection."
type OrdersCollectionSegment {
  "Information to aid in pagination."
  pageInfo: CollectionSegmentInfo!
  "A flattened list of the items."
  items: [OrderListItem!]
  totalCount: Int! @cost(weight: "10")
}

type ProductListItem @key(fields: "id") {
  id: UUID!
}

input DecimalOperationFilterInput {
  eq: Decimal @cost(weight: "10")
  neq: Decimal @cost(weight: "10")
  in: [Decimal] @cost(weight: "10")
  nin: [Decimal] @cost(weight: "10")
  gt: Decimal @cost(weight: "10")
  ngt: Decimal @cost(weight: "10")
  gte: Decimal @cost(weight: "10")
  ngte: Decimal @cost(weight: "10")
  lt: Decimal @cost(weight: "10")
  nlt: Decimal @cost(weight: "10")
  lte: Decimal @cost(weight: "10")
  nlte: Decimal @cost(weight: "10")
}

input IntOperationFilterInput {
  eq: Int @cost(weight: "10")
  neq: Int @cost(weight: "10")
  in: [Int] @cost(weight: "10")
  nin: [Int] @cost(weight: "10")
  gt: Int @cost(weight: "10")
  ngt: Int @cost(weight: "10")
  gte: Int @cost(weight: "10")
  ngte: Int @cost(weight: "10")
  lt: Int @cost(weight: "10")
  nlt: Int @cost(weight: "10")
  lte: Int @cost(weight: "10")
  nlte: Int @cost(weight: "10")
}

input ListFilterInputTypeOfOrderItemListItemFilterInput {
  all: OrderItemListItemFilterInput @cost(weight: "10")
  none: OrderItemListItemFilterInput @cost(weight: "10")
  some: OrderItemListItemFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input OrderItemListItemFilterInput {
  and: [OrderItemListItemFilterInput!]
  or: [OrderItemListItemFilterInput!]
  productId: UuidOperationFilterInput
  product: ProductReferenceFilterInput
  quantity: IntOperationFilterInput
  price: DecimalOperationFilterInput
}

input OrderListItemFilterInput {
  and: [OrderListItemFilterInput!]
  or: [OrderListItemFilterInput!]
  id: UuidOperationFilterInput
  customerId: UuidOperationFilterInput
  orderName: StringOperationFilterInput
  itemCount: IntOperationFilterInput
  totalPrice: DecimalOperationFilterInput
  items: ListFilterInputTypeOfOrderItemListItemFilterInput
}

input OrderListItemSortInput {
  id: SortEnumType @cost(weight: "10")
  customerId: SortEnumType @cost(weight: "10")
  orderName: SortEnumType @cost(weight: "10")
  itemCount: SortEnumType @cost(weight: "10")
  totalPrice: SortEnumType @cost(weight: "10")
}

input ProductReferenceFilterInput {
  and: [ProductReferenceFilterInput!]
  or: [ProductReferenceFilterInput!]
  id: UuidOperationFilterInput
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String @cost(weight: "10")
  neq: String @cost(weight: "10")
  contains: String @cost(weight: "20")
  ncontains: String @cost(weight: "20")
  in: [String] @cost(weight: "10")
  nin: [String] @cost(weight: "10")
  startsWith: String @cost(weight: "20")
  nstartsWith: String @cost(weight: "20")
  endsWith: String @cost(weight: "20")
  nendsWith: String @cost(weight: "20")
}

input UuidOperationFilterInput {
  eq: UUID @cost(weight: "10")
  neq: UUID @cost(weight: "10")
  in: [UUID] @cost(weight: "10")
  nin: [UUID] @cost(weight: "10")
  gt: UUID @cost(weight: "10")
  ngt: UUID @cost(weight: "10")
  gte: UUID @cost(weight: "10")
  ngte: UUID @cost(weight: "10")
  lt: UUID @cost(weight: "10")
  nlt: UUID @cost(weight: "10")
  lte: UUID @cost(weight: "10")
  nlte: UUID @cost(weight: "10")
}

enum ScalarSerializationType {
  STRING
  BOOLEAN
  INT
  FLOAT
  OBJECT
  LIST
}

enum SortEnumType {
  ASC
  DESC
}

"The `Decimal` scalar type represents a decimal floating-point number with high precision."
scalar Decimal
  @serializeAs(type: FLOAT)
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/decimal.html")

scalar FieldSelectionSet

"The `UUID` scalar type represents a Universally Unique Identifier (UUID) as defined by RFC 9562."
scalar UUID
  @serializeAs(
    type: STRING
    pattern: "^[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}$"
  )
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/uuid.html")

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"""
The @key directive is used to designate an entity's unique key,
which identifies how to uniquely reference an instance of
an entity across different source schemas.
"""
directive @key("The field selection set syntax." fields: FieldSelectionSet!) repeatable on
  | OBJECT
  | INTERFACE

"The purpose of the `@listSize` directive is to either inform the static analysis about the size of returned lists (if that information is statically available), or to point the analysis to where to find that information."
directive @listSize(
  "The `assumedSize` argument can be used to statically define the maximum length of a list returned by a field."
  assumedSize: Int
  "The `slicingArguments` argument can be used to define which of the field's arguments with numeric type are slicing arguments, so that their value determines the size of the list returned by that field. It may specify a list of multiple slicing arguments."
  slicingArguments: [String!]
  "The `slicingArgumentDefaultValue` argument can be used to define a default value for a slicing argument, which is used if the argument is not present in a query."
  slicingArgumentDefaultValue: Int
  "The `sizedFields` argument can be used to define that the value of the `assumedSize` argument or of a slicing argument does not affect the size of a list returned by a field itself, but that of a list returned by one of its sub-fields."
  sizedFields: [String!]
  "The `requireOneSlicingArgument` argument can be used to inform the static analysis that it should expect that exactly one of the defined slicing arguments is present in a query. If that is not the case (i.e., if none or multiple slicing arguments are present), the static analysis may throw an error."
  requireOneSlicingArgument: Boolean = true
) on FIELD_DEFINITION

directive @serializeAs(
  "The primitive type a scalar is serialized to."
  type: [ScalarSerializationType!]!
  "The ECMA-262 regex pattern that the serialized scalar value conforms to."
  pattern: String
) on SCALAR

directive @shareable repeatable on OBJECT | FIELD_DEFINITION