services:
  postgres:
    image: postgres:18

  seq:
    image: datalust/seq:latest

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:management

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    ports:
      - "5000:8080"

  web-client:
    image: ${DOCKER_REGISTRY-}web-client
    build:
      context: ./web-client
      dockerfile: Dockerfile

volumes:
  postgres_eshopdb:
  angular_node_modules:






  # api:
  #   image: ${DOCKER_REGISTRY-}api
  #   build:
  #     context: .
  #     dockerfile: Bootstrapper/Api/Dockerfile
