services:
  postgres:
    image: postgres:18

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:management

  keycloak:
    image: ${DOCKER_REGISTRY-}keycloak-organizations
    pull_policy: never
    build:
      context: .
      dockerfile: docker-config/keycloak/Dockerfile

  keycloak-configurator:
    image: node:24-alpine

  loki:
    image: grafana/loki:3.7.7

  tempo:
    image: grafana/tempo:3.0.3

  prometheus:
    image: prom/prometheus:v3.14.0

  grafana:
    image: grafana/grafana:13.2.0

  alloy:
    image: grafana/alloy:v1.18.0

  observability-volume-init:
    image: alpine:3.22

  api:
    image: ${DOCKER_REGISTRY-}api
    pull_policy: never
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    ports:
      - "5004:8080"

  graphql-gateway:
    image: ${DOCKER_REGISTRY-}graphql-gateway
    pull_policy: never
    build:
      context: .
      dockerfile: Bootstrapper/Gateway/Dockerfile
    ports:
      - "5002:8080"

  graphql-gateway-configurator:
    image: mcr.microsoft.com/dotnet/sdk:10.0

  web-client:
    image: ${DOCKER_REGISTRY-}web-client
    pull_policy: never
    build:
      context: ./web-client
      dockerfile: Dockerfile

volumes:
  postgres_eshopdb:
  angular_node_modules:
  fusion_gateway:
  audit_logs:
  alloy_data:
  grafana_data:
  loki_data:
  prometheus_data:
  tempo_data:






  # api:
  #   image: ${DOCKER_REGISTRY-}api
  #   build:
  #     context: .
  #     dockerfile: Bootstrapper/Api/Dockerfile
